### ISSUE TITLE
Implement pgvector in embedding helper

### ISSUE THREAD

**Issue by uogbuji** [OoriData/OgbujiPT#26]
We've been using [Qdrant](https://qdrant.tech/) in memory, but it's time to move to a grown DBMS. Start by trying out PGVector [vis its Python support](https://github.com/pgvector/pgvector-python).

**Comment by uogbuji** [comment]
Grab bag of resources so far:

* [pgvector](https://github.com/pgvector/pgvector)
* [pgvector-python](https://github.com/pgvector/pgvector-python)
* [Postgres with Docker and Docker compose a step-by-step guide for beginners](https://geshan.com.np/blog/2021/12/docker-postgres/)
* [Uncovering the Power of Vector Databases with pgvector: An Introduction
](https://www.datascienceengineer.com/blog/post-what-is-pgvector) - general conceptual intro that then delves into a bunch of useful SQL specifics
* [Vector Similarity Search in Postgres with bit.io and pgvector](https://innerjoin.bit.io/vector-similarity-search-in-postgres-with-bit-io-and-pgvector-c58ac34f408b) - Medium, but not paywalled. I think the bit.io bits can just be ignored. The product is dead, anyway. Some nice code examples with using psycopg for the queries
* [Vecs intro](https://colab.research.google.com/github/supabase/supabase/blob/master/examples/ai/vector_hello_world.ipynb#scrollTo=oQeCPgFKf3MQ) - colab notebook intro to vecs, a python client for managing and querying vector stores in PostgreSQL/pgvector extension
* [Building AI-powered apps on Google Cloud databases using pgvector, LLMs and LangChain
](https://cloud.google.com/blog/products/databases/using-pgvector-llms-and-langchain-with-google-cloud-databases)

**Comment by uogbuji** [comment]
Prior, interrupted work using the Docker install (sofola-remote context), as mentioned in the [pgvector README](https://github.com/pgvector/pgvector):

```sh
docker pull ankane/pgvector
```

Very first Docker Run needs the master password set up. 

```sh
docker run -d -it --name pgvector -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=$PGPASSWD ankane/pgvector
```

We have $PGPASSWD defined in our corporate secrets store.

In theory subsequent runs are just:

```sh
docker run -d ankane/pgvector
```

But it seems to be requiring the master password every time, maybe as a security mechanism, because it's via Docker?

I used this useful PG/Docker guide, with small mods because it's for the regular PG images, rather than the pgvector one. Enter the running container, in order to use psql

```sh
docker exec -it pgvector /bin/sh
# Now we should be in the container's shell
psql --username postgres
```

Created a DB & set up the pgvector extension:

```sql
CREATE DATABASE docuvectors;
# Do this once in each database where you want to use it
CREATE EXTENSION vector;
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));
```

Can now see this running `\l`. Remember it's `\q` to exit psql.

**Comment by choccccy** [comment]
superseded by #33
