### ISSUE TITLE
PGVector implementation

### ISSUE THREAD

**Issue by kaischuygon** [OoriData/OgbujiPT#33]

**Comment by Aidan-Reese** [comment]
Updated my .env to resemble this

DISCORD_TOKEN=
LLM_HOST=
LLM_PORT=
LLM_TEMP=
DB_USER=
DB_PASSWORD=
DB_NAME=
DB_HOST=
DB_PORT=

Information found for DB is on Oori-PGvector on 1pass

**Comment by Aidan-Reese** [comment]
Error that were running into:

```sh
DETAIL:  Could not open extension control file "/usr/share/postgresql/15/extension/vector.control": No such file or directory.
HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

Yesterday we were successfully able to connect to the db with an image that we thought included PGvector but this error implies otherwise.  Will need to find out what's really going on here...

**Comment by choccccy** [comment]
ok, getting the issues with installing the vector extension seemingly no matter where you run it from:

![Image](https://github.com/OoriData/OgbujiPT/assets/12983495/7dda2044-3530-441b-b50a-d586c1db6082)

**Comment by choccccy** [comment]
restarting the postgres container seems to have fixed things; Kai thinks that this is because we have just failed to do so since adjusting the image we're pulling to one that has pgvector installed.

**Comment by choccccy** [comment]
alright, got a super rudementary return from a table that we created. no vector functionality yet, but we're happy with it for now (https://github.com/OoriData/OgbujiPT/commit/54052212fa9d4e3c826999942ad5d01180b4913b). We should investigate sorting out list weirdness with pgvector-python, and once we have a robust example program, we should take some of the more boilerplate functionality and make it into methods of the PGv class in `embedding_helper.py`
