### ISSUE TITLE
0.6.0 release

### ISSUE THREAD

**Issue by choccccy** [OoriData/OgbujiPT#47]
- [x] Added branding logo to top of readme
- [ ] ~~Added chroma embedding demo~~
- [x] PGvector embedding fixes (#45)
- [x] Fixes to model introspection
  - [x] Move OAI response structure handling helpers
  - [x] api_base management polishing; made it easier to switch between local and OpenAI APIs
- [x] Fixed testing mocking for `test/test_llm_wrapper.py`
- [x] Land #40. Don't forget to update the CHANGELOG.md

**Comment by uogbuji** [comment]
Kicking this can: Added chroma embedding demo

**Comment by uogbuji** [comment]
[Released.](https://github.com/OoriData/OgbujiPT/releases/tag/0.6.0). Just needs PyPI release, then we can close this, @choccccy?

**Comment by uogbuji** [comment]
[PyPI released](https://pypi.org/project/OgbujiPT/0.6.0/)
