### ISSUE TITLE
Create a model style for open-llama-open-instruct

### ISSUE THREAD

**Issue by uogbuji** [OoriData/OgbujiPT#5]
We installed TheBloke/open-llama-7b-open-instruct-GPTQ on our Ooba (see [Reddit thread](https://www.reddit.com/r/LocalLLaMA/comments/145e9m3/the_first_instruction_tuning_of_open_llama_is_out/)). It seems you can prompt it with a direct prompt, or [alpaca-instruct](#3) style, but I'm confirming this on Ooba Discord.

@choccccy, useful task for you. We might well actually just also put it into [alpaca.py](https://github.com/uogbuji/OgbujiPT/blob/main/pylib/model_style/alpaca.py) and rename that file llama_alpaca.py (LLaMA comes before Alpaca in LLM lineage).

**Comment by uogbuji** [comment]
Some notes I found on Reddit; nothing on straight LLaM, though.

> vicuna (used by e.g. stable vicuna)

```
### Human: {{prompt}}
### Assistant:{{gen}}
```

> wizard (used by e.g. wizard vicuna)

```
USER: {{prompt}}
ASSISTANT:{{gen}}
```

> alpaca (used by e.g. gpt4-x-vicuna)

```
### Instruction: {{prompt}}
### Input: {{input}}
### Response:{{gen}}
```

**Comment by choccccy** [comment]
We will probably eventually have more modular and more universal prompting templates, but for now we have most of the usual gamut of prompting covered already.
