### ISSUE TITLE
Where is the support for Functions? 

### ISSUE THREAD

**Issue by stevechappell2000** [OoriData/OgbujiPT#50]
I can nothing documenting how to upgrade or how to use the functions array in the new chat.completions call.

**Comment by uogbuji** [comment]
Hi, sorry, we're pretty heads down trying to get the 0.6.0 release out, and I haven't had a chance to catch up on tickets.

Function calling should work transparently. We don't really provide any particular, fancy features, but below, for example is a simple script using it. It's based on an old script I had lying around on my drive, based on some example I'd found online at some point. You probably need to run it using the `49-pythonopenai-breaking` branch, for now, given OpenAI's breaking changes from Monday's Dev Day. As soon as we release 0.6.0 it should just work.

```py
import os
import json
from typing import List
from pydantic import BaseModel
from ogbujipt.llm_wrapper import openai_chat_api, prompt_to_chat

# PyDantic schema for function spec output
class StepByStepAIResponse(BaseModel):
    title: str
    steps: List[str]

llm_api = openai_chat_api(model='gpt-4')

messages=[
       {"role": "user", "content": "Explain how to assemble a PC"}
    ]

functions=[
        {
          "name": "get_answer_for_user_query",
          "description": "Get user answer in series of steps",
          "parameters": StepByStepAIResponse.schema()
        }
]

function_call={"name": "get_answer_for_user_query"}

resp = llm_api(messages=messages, functions=functions, function_call=function_call)
resp.choices[0].message.function_call
resp.choices[0].message.function_call.arguments
```

**Comment by choccccy** [comment]
howdy @stevechappell2000! I think @uogbuji has demonstrated that OgbujiPT is natively able to utilize function calls. We definitely should have a demo and more documentation on the subject though.

Feel free to reopen this ticket if you feel as though this wasn't the solution you're looking for!

**Comment by uogbuji** [comment]
@stevechappell2000 I added a demo for function calling. If you weren't sure how to do that, probably true for others. Thanks for raising the issue!

@choccccy, what do you think? I just left this demo as a simple script, rather than a command-line program (e.g. using click). I think that' probably OK since we have plenty of examples of the latter. We'll want to be adding more demos, and reducing the friction to doing so makes sense to me, but wanted to see what you think.

**Comment by choccccy** [comment]
Yeah, makes sense. Making/polishing/fixing demos always seems to get shoved to the back burner, so minimizing friction seems like the right call.
