### ISSUE TITLE
ogbujipt.embedding.pgvector.PGVectorHelper.insert_many not working

### ISSUE THREAD

**Issue by chimezie** [OoriData/OgbujiPT#54]
If you pass it the expected list of tuples of the form:

- content
- permission
- title
- page_numbers
- tags

It raises the exception:

> asyncpg.exceptions._base.InterfaceError: the server expects 5 arguments for this query, 6 were passed

Looking at INSERT_DOCS in that module, it is not expecting the 'permission' item in the tuple.  It looks like recent changes to remove the permission from the embedding table didn't update this method and introduced a regression.  It would probably be good to have a unit test for this function to prevent such changes from breaking it.

**Comment by choccccy** [comment]
included a unit test and merged it into your branch as of commit c497918

**Comment by choccccy** [comment]
this should be solved as of the merge from `Pgvector bigdata insert and search` and released in version 0.7.0
