### ISSUE TITLE
Change metadata_json to metadata for `chatlog` table.

### ISSUE THREAD

**Issue by kaischuygon** [OoriData/OgbujiPT#63]
While working on an Oori product we were cleaning up naming & noticed this bit of redundancy from OgbujiPT.

See (if you have access): https://github.com/OoriData/OoriChat/issues/97.

**Comment by uogbuji** [comment]
Oops! We don't seem to have a test suite for `MessageDB`. I'll string one together. That makes me think: for consistency, we sometimes refer to the items as messages, sometimes as chat. I'm thinking "message" is more generic, and broader, even though we're primarily using this for online chat ATM. I propose keeping the class name as `MessageDB`, but changing e.g. "chatlog" to "message_log" throughout the code. Luckily, this latter change won't really affect anything at the interface level, but @kaischuygon & @choccccy just wanted a quick check what you think.

**Comment by uogbuji** [comment]
Hmm. Test suite still not working in CI. @kaischuygon do you have a beat to investigate? https://github.com/OoriData/OgbujiPT/actions/runs/7358394631

**Comment by kaischuygon** [comment]
I can investigate later today.

**Comment by kaischuygon** [comment]
@uogbuji Seemed to be an issue with openai's API, they added `logprobs` to `Choice` that pydandic was expecting. Set to `None` per [this page](https://platform.openai.com/docs/guides/text-generation/chat-completions-api) and seems to be working again.

**Comment by kaischuygon** [comment]
commit https://github.com/OoriData/OgbujiPT/commit/593df29f2e3460f105ef42b50404879b6a5747ad succeeded

**Comment by kaischuygon** [comment]
This run https://github.com/OoriData/OgbujiPT/actions/runs/7360059329 succeeded with this change.

**Comment by uogbuji** [comment]
> @uogbuji Seemed to be an issue with openai's API, they added `logprobs` to `Choice` that pydandic was expecting. Set to `None` per [this page](https://platform.openai.com/docs/guides/text-generation/chat-completions-api) and seems to be working again.

Oh weird! Not what I thought it was at all, from looking at the CI logs, but I'll take the W!

**Comment by uogbuji** [comment]
There turned out to be much more packed into this issue than expected, once I decided to add the missing test cases.
