### ISSUE TITLE
Enhancements to Word Loom—item metadata

### ISSUE THREAD

**Issue by uogbuji** [OoriData/OgbujiPT#77]
Having spent some time working with [Word Loom](https://github.com/OoriData/OgbujiPT/wiki/Word-Loom:-A-format-for-managing-language-for-AI-LLMs-(including-prompts)) lately, I have a few enhancements in mind. @chimezie, would love your thoughts.

First of all, I'd like to to formalize the name "language item" (just "item" for short) for each entity that's specified with a [TOML table](https://toml.io/en/v1.0.0#table).

I'd like to add support for language item metadata. In effect, any other key/value pairs within the TOML table for an item would be passed in as metadata associated with that item to the Word Loom implementation. There is actually an example of this already in the Word Loom "spec" (`[i18n_context] / source`), but I completely omitted any discussion of that. I would just add the formalization that it would be preserved as item metadata. Such metadata would support e.g. control features for how language items are selected & processed for LLM prompts.

Then probably the most controversial bit. In order to lower the footprint of English language in Word Loom, and also free up a couple of other metadata keys, I would deprecate the `text` key in favor of just `_` (inspired by gettext) and deprecate the `markers` key in favor of `_m`.

**Comment by uogbuji** [comment]
Oh, I would also say that all keys starting with `_` are reserved for (possibly future) Word Loom-specced use.

**Comment by uogbuji** [comment]
Furthermore, alternate languages would be specified using `_` followed by an [IETF language code](https://en.wikipedia.org/wiki/IETF_language_tag), e.g. `_fr`.

**Comment by uogbuji** [comment]
Above commit implements changes discussed above (on a branch until agreed & ready 😊)

**Comment by chimezie** [comment]
TOML table metadata would be a welcome addition for declarative prompt composition using Word Loom. Deprecating the `text` and `markers` keys in that way makes sense, given the proposal for indicating metadata and seems justified as a breaking change.
